import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useSession } from "next-auth/react";
import DiscList from "~/components/DiscList";

import { api } from "~/utils/api";

const Home: NextPage = () => {

  const { data: session } = useSession();
  const { data: bagCount = 0 } = api.bag.numberOfBags.useQuery()
  const { data: isUserAdmin } = api.user.isUserAdmin.useQuery()

  return (
    <>
      <Head>
        <title>Discbag | Create your bag</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="md:container md:mx-auto px-4">
        <div className="flex flex-col md:flex-row justify-between mt-12">
          <h1 className="text-4xl font-semibold">Welcome {session?.user.name}</h1>
          <div className="flex mt-6 md:mt-0 gap-4">
            <Link href="/bag" className="flex justify-center items-center bg-indigo-500 hover:bg-indigo-400 text-sm text-indigo-50 px-4 py-2 rounded">View bag ({bagCount})</Link>
            {isUserAdmin?.role === 'ADMIN' && <Link href="/discs/create" className="flex justify-center items-center bg-emerald-500 hover:bg-emerald-400 text-sm text-emerald-50 px-4 py-2 rounded">Create disc</Link>}
          </div>
        </div>
        <DiscList />
        </div>
    </>
  );
};

export default Home;
